<br><br>
<br><br><br><br><br>
<img src="images/TensorFlow.png" alt="TensorFlow" style="float: center; width : 50%; margin-right:2px">
<h1 style="color: #444c64;font-family: Arial;font-size: 3rem; float: right;"><b>SALHI Elmootez</b></h1>
<br><br><br><br><br><br>
<h2 style="color: #444c64; font-size: 4rem; font-family:Georgia;"> Cours 1 : Les notions de bases</h2>
<br><br>

<h2 style="font-family:Georgia;">1. C'est quoi TensorFlow ?</h2>

<p style="font-family:Georgia;">TensorFlow est une bibliothèque de machine learning open-source de bout en bout pour prétraiter les données, modéliser les données et servir les modèles (les mettre entre les mains des autres).</p>

In [4]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.10.0


<h2 style="font-family:Georgia;">2. Introduction sur les Tenseurs</h2><br><br><br>
<img src="images/tensorVSmatrix.png" alt="Tensor" style="float: center; width : 70%"><br><br>

<p style="font-family:Georgia; text-align:justify">Un tenseur en deep learning est un objet de base utilisé dans les frameworks de deep learning comme TensorFlow. Ils sont utilisés pour stocker presque tout dans l’apprentissage en profondeur: données d’entrée, poids, biais, prédictions, etc. Un tenseur est un tableau multidimensionnel qui stocke un type spécifique de valeur. Par exemple, une image en niveaux de gris est un tenseur 2D, une image couleur un tenseur 3D. La plus grande différence entre un tableau numpy et un tenseur est qu’un tenseur peut fonctionner sur CPU ou GPU. En apprentissage profond, nous avons besoin de performances pour calculer de nombreuses multiplications matricielles de manière hautement parallèle</p><br>

<img src="images/tensors.png" alt="Tensor" style="float: center; width : 60%">

<h2 style="font-family:Georgia;">3. Creation des Tenseurs avec <code>tf.constant()</code></h2><br>

<h3 style="font-family:Georgia;">3.1 Scalaire</h3><br>

In [5]:
# Creer un scalaire
scalaire = tf.constant(7)
scalaire

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Verifier les dimensions du scalaire
scalaire.ndim

0

<h3 style="font-family:Georgia;">3.2 Vecteur</h3><br>

In [9]:
vecteur = tf.constant([10,8])
vecteur

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8])>

In [10]:
vecteur.ndim

1

<h3 style="font-family:Georgia;">3.3 Matrice</h3><br>

In [12]:
matrice = tf.constant([[1,2],
                       [5,8]])
matrice

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 8]])>

In [13]:
matrice.ndim

2

<h3 style="font-family:Georgia;">! Data type</h3><br>
<p style="font-family:Georgia; text-align:justify">Par défaut, TensorFlow crée des tenseurs avec un type de données <code>int32</code> ou <code>float32</code>. Ceci est connu sous le nom de précision 32 bits (plus le nombre est élevé, plus le nombre est précis, plus il prend de l’espace sur l'ordinateur).</p><br>
<p style="font-family:Georgia; text-align:justify"> La précision d’une quantité numérique est une mesure du détail dans lequel la quantité est exprimée. Cela se mesure généralement en bits, mais parfois en chiffres décimaux. Cela est lié à la précision en mathématiques, qui décrit le nombre de chiffres utilisés pour exprimer une valeur.</p>
<p style="font-family:Georgia; text-align:justify"> Certains des formats de précision standardisés sont :</p>
<ul>
    <li><a href="https://en.wikipedia.org/wiki/Half-precision_floating-point_format">Format de virgule flottante à demi-précision</a></li>
    <li><a href="https://en.wikipedia.org/wiki/Single-precision_floating-point_format">Format de virgule flottante à simple précision</a></li>
    <li><a href="https://en.wikipedia.org/wiki/Precision_(computer_science)">etc ...</a></li>
</ul>

<p style="font-family:Georgia; text-align:justify">Les formats à <b>simple et double précision</b> sont les plus largement utilisés et pris en charge sur presque toutes les plateformes. L’utilisation du format à demi-précision a augmenté, en particulier dans le domaine de l’apprentissage automatique, car de nombreux algorithmes d’apprentissage automatique sont intrinsèquement tolérants aux erreurs.</p>

In [17]:
# Modification du Data Type : 

nvllMatrice = tf.constant([[5,6],
                           [9,10],
                          [15,18]],dtype=tf.float16)
nvllMatrice

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 5.,  6.],
       [ 9., 10.],
       [15., 18.]], dtype=float16)>

<p style="font-family:Georgia; text-align:justify">Malgre que la matrice contient plus de nombres elle a toujours la meme dimension !</p>

In [18]:
nvllMatrice.ndim

2

<h3 style="font-family:Georgia;">3.4 Tenseur</h3><br>

In [22]:
# Exemple 1
tenseur = tf.constant([[[1,2],
                       [3,4]],
                     [[5,6],
                      [7,8]],
                     [[9,10],
                      [11,12]]])
tenseur

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])>

In [21]:
tenseur.ndim

3

In [23]:
# Exemple 2
tenseur = tf.constant([[[1,2,12],
                       [3,4,34]],
                     [[5,6,56],
                      [7,8,78]],
                     [[9,10,910],
                      [11,12,1112]]])
tenseur

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   1,    2,   12],
        [   3,    4,   34]],

       [[   5,    6,   56],
        [   7,    8,   78]],

       [[   9,   10,  910],
        [  11,   12, 1112]]])>

In [24]:
tenseur.ndim

3

<p style="font-family:Georgia; text-align:justify">Toutes les variables ci-dessus que nous avons créées sont en fait des <b>Tenseurs</b>. Mais on peut également les appeler par leurs différents noms (ceux que nous leur avons donnés):</p>

<ul>
    <li><b>Scalaire :</b> un seul nombre</li>
    <li><b>Vecteur :</b> un nombre avec une direction</li>
    <li><b>Matrice :</b> un tableau bidimensionnel</li>
    <li><b>Tenseur :</b> un tableau de nombres à n dimensions (où n peut être n’importe quel nombre)</li>
</ul>

<h2 style="font-family:Georgia;">4. Creation des Tenseurs avec <code>tf.Variable()</code></h2><br>

<p style="font-family:Georgia; text-align:justify">La différence entre <code>tf.Variable()</code> et <code>tf.constant()</code> est que les tenseurs créés avec <code>tf.constant()</code> sont immuables (ne peuvent pas être modifiés, ne peuvent être utilisés que pour créer un nouveau tenseur), alors que les tenseurs créés avec <code>tf.Variable()</code> sont modifiables (peuvent être modifiés).</p>

In [27]:
tenseur_variable = tf.Variable([15,20])
tenseur_constant = tf.constant([30,35])

tenseur_variable, tenseur_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 35])>)

In [28]:
# Essayons de changer une valeur du tenseur_variable
tenseur_variable[0] = 1

TypeError: 'ResourceVariable' object does not support item assignment

In [32]:
# Pour assigner une nouvelle valeur il faut utiliser la fonction "assign" : 
tenseur_variable[0].assign(1)
tenseur_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 1, 20])>

In [33]:
# Essayons de modifier le tenseur_constant : 
tenseur_constant[0].assign(2)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<h2 style="font-family:Georgia;">5. Creation des Tenseurs aleatoires (random) <code>tf.random.Generator</code> class</h2><br>
<p style="font-family:Georgia;font-size:1.5rem; text-align:justify"><b>Pourquoi nous utilisons des Tenseurs aleatoire ?</b> </p>

<p style="font-family:Georgia; text-align:justify">Les tenseurs aléatoires, sont de taille arbitraire contenant des nombres aléatoires, sont utilisés par les réseaux de neurones pour initialiser leurs poids (modèles) lorsqu’ils tentent d’apprendre à partir des données.</p>

In [10]:
# Creyons un tenseur aleatoire

random_1 = tf.random.Generator.from_seed(23)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892],
       [-1.5700307 ,  0.4457582 ],
       [ 0.10944034, -0.8035768 ]], dtype=float32)>

In [13]:
# Creyons un deuxieme tenseur

random_2 = tf.random.Generator.from_seed(23)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892],
       [-1.5700307 ,  0.4457582 ],
       [ 0.10944034, -0.8035768 ]], dtype=float32)>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify"><b>Mais Pourquoi on obtient deux tenseurs identiques ?? </b> </p>
<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">Les tenseurs aléatoires que nous avons créés sont en fait des nombres pseudo-aléatoires (ils apparaissent comme aléatoires, mais ne le sont pas vraiment). Si nous définissons un seed, nous obtiendrons les mêmes nombres aléatoires. </p>
<br>
<img src="images/dumber.gif" alt="Tensor" style="float: left; width : 50%"><br><br>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">Si on souhaite avoir des tenseurs differents, il suffit de changer la valeur de seed</p>

In [15]:
# Creyons deux tenseurs differents :

random_3 = tf.random.Generator.from_seed(23)
random_3 = random_3.normal(shape=(3,2))

random_4 = tf.random.Generator.from_seed(99)
random_4 = random_4.normal(shape=(3,2))

random_3, random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892],
        [-1.5700307 ,  0.4457582 ],
        [ 0.10944034, -0.8035768 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.9934515 ,  1.4369737 ],
        [ 1.1249138 ,  0.77698714],
        [-0.90112925, -0.0175216 ]], dtype=float32)>)

In [16]:
random_3 == random_4

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

<h2 style="font-family:Georgia;">6. Melanger l'ordre d'un Tenseur "Shuffling"</h2><br>
<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">L'ordre pourrait affecter la façon dont un réseau de neurones apprend (il pourrait y avoir un overfit en apprenant l’ordre des données), à la place, il pourrait être une bonne idée de melanger les données.</p>

In [27]:
tenseur = tf.random.uniform(shape=[4,4], minval=1, maxval=10, dtype=tf.int64)
tenseur

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[3, 1, 3, 8],
       [5, 6, 9, 4],
       [5, 4, 6, 4],
       [1, 3, 1, 6]], dtype=int64)>

In [29]:
tf.random.shuffle(tenseur) # modification de l'ordre des lignes 

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[5, 4, 6, 4],
       [1, 3, 1, 6],
       [3, 1, 3, 8],
       [5, 6, 9, 4]], dtype=int64)>

<h2 style="font-family:Georgia;">7. Autres facons pour creer des Tenseurs <code>tf.zeros</code> et <code>tf.ones</code></h2>

In [4]:
tf.ones(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<h2 style="font-family:Georgia;">8. Manipulation des tenseurs</h2>

<h3 style="font-family:Georgia;">8.1 Addition :</h3><br>

In [18]:
tenseur = tf.constant([[10,15],
                       [14,10]])
tenseur + 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 115],
       [114, 110]])>

In [19]:
# Notre tenseur de base :
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [14, 10]])>

<h3 style="font-family:Georgia;">8.2 Soustraction :</h3><br>

In [21]:
tenseur - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 5],
       [4, 0]])>

<h3 style="font-family:Georgia;">8.2 Multiplication <code>(tf.multiply)</code> :</h3><br>

In [22]:
tenseur * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 150],
       [140, 100]])>

In [24]:
tf.multiply(tenseur,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 150],
       [140, 100]])>

In [25]:
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [14, 10]])>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">L’une des opérations les plus courantes en machine learning est la multiplication des matrices.
TensorFlow met en œuvre cette fonctionnalité de multiplication de matrices avec la méthode <code>tf.matmul().</code> <br><br>Pour pouvoir effectuer des multiplications entre les matrices il faut qu'elles respectent la forme suivante : <code>(a,b) @ (b,a)</code><br>La matrice <code>(a,b)</code></p>

<ul style="font-family:Georgia;font-size:1.5rem; text-align:justify">
    <li><code>a</code> correspond au nombre de lignes</li>
    <li><code>b</code> correspond au nombre de colonnes</li>   
</ul>
<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">La matrice resultante est de cette forme : <code>(a,a)</code></p>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">Exemples : </p>

<ul>
    <li><code>(5,4) @ (4,5)</code> = <code>(5,5)</code></li>
    <li><code>(3,2) @ (2,3)</code> = <code>(3,3)</code></li>
</ul>

In [26]:
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [14, 10]])>

In [34]:
print(tenseur.shape)
tf.matmul(tenseur,tenseur)

(2, 2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[310, 300],
       [280, 310]])>

In [54]:
matrice1 = np.arange(1,13)
matrice2 = np.arange(10,22)

In [69]:
matrice1 = matrice1.reshape(3,4)
matrice2 = matrice2.reshape(4,3)

print(f"""Matrice 1 :
{matrice1}

shape : {matrice1.shape}""")
print("______________\n")
print(f"""Matrice 2 :
{matrice2}

shape: {matrice2.shape}""")

Matrice 1 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape : (3, 4)
______________

Matrice 2 :
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]

shape: (4, 3)


In [73]:
# On multipliant ces deux matrices ensemble on s'attend a cette forme : (3,3)

matrice3 = tf.matmul(matrice1,matrice2)
print(f"""Matrice 3 :\n 
{matrice3}\n""")
print(f"shape = {matrice3.shape}")

Matrice 3 :
 
[[160 170 180]
 [392 418 444]
 [624 666 708]]

shape = (3, 3)


In [78]:
print(f"""Shape Matrice 1 : 
{matrice1.shape}

Shape Matrice 2 : 
{matrice2.shape}
""")

Shape Matrice 1 : 
(3, 4)

Shape Matrice 2 : 
(4, 3)



In [76]:
# Mutlipliant la matrice 2 par la matrice 1

matrice3 = tf.matmul(matrice2,matrice1)
print(f"""Matrice 3 :\n 
{matrice3}\n""")
print(f"shape = {matrice3.shape}")

Matrice 3 :
 
[[173 206 239 272]
 [218 260 302 344]
 [263 314 365 416]
 [308 368 428 488]]

shape = (4, 4)


<h3 style="font-family:Georgia;">8.3 Opérateur Python <code>@</code> :</h3><br>

In [79]:
matrice1 @ matrice2

array([[160, 170, 180],
       [392, 418, 444],
       [624, 666, 708]])

In [81]:
matrice2 @ matrice1

array([[173, 206, 239, 272],
       [218, 260, 302, 344],
       [263, 314, 365, 416],
       [308, 368, 428, 488]])

In [116]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [117]:
X @ Y # les deux matrices ont la meme forme!!

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">On souhaite multiplier nos deux matrices, cependant, elles ne présentent pas la même forme. Par conséquent, nous devons modifier la forme de ces deux matrices. Il existe deux méthodes pour le faire.</p>
<ul style="font-family:Georgia;font-size:1.5rem; text-align:justify">
    <li><code>tf.reshape()</code> : nous permet de redimensionner un tenseur dans une forme définie.</li>
    <li><code>tf.transpose()</code>: permute les dimensions d’un tenseur donné.</li>
</ul>

In [118]:
# Shapes
print("Y :",Y.shape)

Y : (3, 2)


In [119]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [120]:
Y = tf.reshape(Y,(2,3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [121]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [122]:
print("X :",X.shape)

X : (3, 2)


In [123]:
Y @ X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]])>

In [125]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

<h3 style="font-family:Georgia;">Dot product : <code>tf.tensordot()</code></h3>

In [126]:
tf.tensordot(Y,X,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]])>

In [127]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [135]:
print(f"""Reshaped : 
{tf.reshape(X,(2,3))}

Transposed : 
{tf.transpose(X)}""")

Reshaped : 
[[1 2 3]
 [4 5 6]]

Transposed : 
[[1 3 5]
 [2 4 6]]


In [137]:
tf.tensordot(X,tf.transpose(X),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])>

In [139]:
tf.tensordot(X,tf.reshape(X,(2,3)),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

<h2 style="font-family:Georgia;">9. Changer le type de donnees des tenseurs <code>tf.cast()</code></h2>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">Effectuer des calculs avec une précision moindre est avantageux sur les appareils ayant une capacité de calcul limitée, tels que les appareils mobiles. En effet, moins il y a de bits utilisés, moins l’espace requis pour les calculs est important.</p>

In [143]:
A = np.arange(1,4,0.5)
B = np.arange(2,5,0.5)

In [144]:
tf.constant(A)
tf.constant(B)

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([2. , 2.5, 3. , 3.5, 4. , 4.5])>

In [149]:
A = tf.cast(A,dtype = tf.float16)
A

<tf.Tensor: shape=(6,), dtype=float16, numpy=array([2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float16)>

In [152]:
B = tf.cast(B,dtype = tf.float32)
B

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float32)>

<h2 style="font-family:Georgia;">10. Valeur absolue <code>tf.abs()</code></h2>

In [153]:
matrice_abs = np.arange(-30,-10,2)
matrice_abs

array([-30, -28, -26, -24, -22, -20, -18, -16, -14, -12])

In [154]:
matrice_abs = tf.constant(matrice_abs)

In [157]:
matrice_abs = tf.abs(matrice_abs)

<h2 style="font-family:Georgia;">11. <code>min</code> <code>max</code> <code>mean</code> <code>sum</code> </h2>

In [173]:
matrice = np.random.randint(0, 100, 100)
matrice

array([11, 20, 31, 77, 35, 58, 15, 89, 43, 33, 15, 54,  1, 36,  0, 76, 32,
       80, 99, 27, 94, 98, 55, 16, 56, 23, 76, 89, 19, 42, 29, 15, 64,  6,
       47, 35, 99, 39, 77,  9, 49, 87, 41, 23, 70, 60, 32, 75, 95, 24, 64,
       47, 80, 41, 56, 30, 90, 81, 92, 49, 67, 65, 52, 99, 42, 40, 15, 94,
       10, 26, 86, 69, 94, 23, 17, 39, 79, 92, 86, 31, 80,  6, 50, 48, 27,
       72, 41, 21, 84, 17, 96, 73, 67, 17,  0, 51, 25, 84, 54, 92])

In [174]:
#Chercher la valeur minimale dans un tenseur

tf.reduce_min(matrice)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [175]:
#Cherhcer la valeur maximale

tf.reduce_max(matrice)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [176]:
#Calculer la moyenne d'un tenseur

tf.reduce_mean(matrice)

<tf.Tensor: shape=(), dtype=int32, numpy=51>

In [177]:
#Calculer la somme d'un tenseur

tf.reduce_sum(matrice)

<tf.Tensor: shape=(), dtype=int32, numpy=5137>

<h2 style="font-family:Georgia;">12. Trouver la position maximale et minimale d'un element dans un tenseur</h2>

In [208]:
tenseur = np.random.random(100)

In [185]:
tenseur = tf.constant(tenseur)

In [186]:
tenseur

<tf.Tensor: shape=(100,), dtype=float64, numpy=
array([0.75978005, 0.15380998, 0.31184891, 0.66930818, 0.64559951,
       0.48826623, 0.925189  , 0.07514326, 0.35518766, 0.67541107,
       0.97439335, 0.45302918, 0.24645476, 0.39249166, 0.7838261 ,
       0.4596718 , 0.36025944, 0.42511656, 0.51739056, 0.54871094,
       0.74365239, 0.47754388, 0.76273869, 0.93326497, 0.71378823,
       0.97885485, 0.42489956, 0.07503836, 0.51499796, 0.22431135,
       0.1523272 , 0.80298135, 0.14477478, 0.01397915, 0.9407614 ,
       0.23474567, 0.2034405 , 0.18300257, 0.30837682, 0.92822711,
       0.32688537, 0.07936209, 0.5895107 , 0.43963539, 0.81700819,
       0.58977474, 0.62005746, 0.13432753, 0.86216224, 0.01703903,
       0.62455273, 0.37279575, 0.70198064, 0.53903341, 0.68067401,
       0.049382  , 0.06331754, 0.55683896, 0.50291726, 0.0971765 ,
       0.78055849, 0.18730769, 0.19411519, 0.16581019, 0.72244948,
       0.22983267, 0.85779552, 0.31934853, 0.95534327, 0.67710777,
       0.92871

In [187]:
# Trouver la position du plus grand element

tf.argmax(tenseur)

<tf.Tensor: shape=(), dtype=int64, numpy=76>

In [188]:
# Trouver la position de l'element le plus petit

tf.argmin(tenseur)

<tf.Tensor: shape=(), dtype=int64, numpy=87>

In [196]:
print(f"""L'element le plus grand = {tf.reduce_max(tenseur)}, a la position {tf.argmax(tenseur)}

L'element le plus petit = {tf.reduce_min(tenseur)}, a la position {tf.argmin(tenseur)}

Autre facons pour trouver la valeur max et min : 

Valeur maximale : {tenseur[tf.argmax(tenseur)]}

Valeur minimale : {tenseur[tf.argmin(tenseur)]}""")

L'element le plus grand = 0.982153136030096, a la position 76

L'element le plus petit = 0.008690788228666091, a la position 87

Autre facons pour trouver la valeur max et min : 

Valeur maximale : 0.982153136030096

Valeur minimale : 0.008690788228666091


<h2 style="font-family:Georgia;">13. Compression d'un tenseur (Squeezing) : <code>tf.squeeze()</code></h2>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">La fonction <code>tf.squeeze()</code> est utilisée pour supprimer les dimensions de taille 1 </p>

In [223]:
tenseur = np.random.randint(0,100,100)

In [224]:
tenseur

array([89, 13, 65, 55, 36, 40, 90, 83, 43, 27, 46, 16, 53, 96,  9, 23, 66,
       24, 34, 72, 24, 68, 43, 80, 99, 20, 49, 51, 26, 79, 48,  4, 81, 47,
       95, 35, 96, 50, 13, 14,  6, 30, 38, 60,  2, 92, 11, 76, 38, 28, 66,
       12, 88, 63, 39, 92, 44, 91, 43, 13, 82,  5,  6, 28, 66, 25, 56, 30,
       47, 21,  0, 79, 65, 86, 90, 95, 41, 42, 13, 20, 96, 87, 77, 76, 61,
       15, 45, 44, 29, 20, 41, 37, 48,  4, 63,  6, 28, 53, 37, 90])

In [235]:
tenseur = tf.sort(tenseur)
tenseur

<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([ 0,  2,  4,  4,  5,  6,  6,  6,  9, 11, 12, 13, 13, 13, 13, 14, 15,
       16, 20, 20, 20, 21, 23, 24, 24, 25, 26, 27, 28, 28, 28, 29, 30, 30,
       34, 35, 36, 37, 37, 38, 38, 39, 40, 41, 41, 42, 43, 43, 43, 44, 44,
       45, 46, 47, 47, 48, 48, 49, 50, 51, 53, 53, 55, 56, 60, 61, 63, 63,
       65, 65, 66, 66, 66, 68, 72, 76, 76, 77, 79, 79, 80, 81, 82, 83, 86,
       87, 88, 89, 90, 90, 90, 91, 92, 92, 95, 95, 96, 96, 96, 99])>

In [236]:
print(tenseur.shape)

(100,)


In [237]:
tenseur = tf.reshape(tenseur,(1,1,1,1,100))

In [238]:
print(tenseur.shape)

(1, 1, 1, 1, 100)


In [239]:
tenseur = tf.squeeze(tenseur)

In [240]:
print(tenseur.shape)

(100,)


In [241]:
tenseur

<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([ 0,  2,  4,  4,  5,  6,  6,  6,  9, 11, 12, 13, 13, 13, 13, 14, 15,
       16, 20, 20, 20, 21, 23, 24, 24, 25, 26, 27, 28, 28, 28, 29, 30, 30,
       34, 35, 36, 37, 37, 38, 38, 39, 40, 41, 41, 42, 43, 43, 43, 44, 44,
       45, 46, 47, 47, 48, 48, 49, 50, 51, 53, 53, 55, 56, 60, 61, 63, 63,
       65, 65, 66, 66, 66, 68, 72, 76, 76, 77, 79, 79, 80, 81, 82, 83, 86,
       87, 88, 89, 90, 90, 90, 91, 92, 92, 95, 95, 96, 96, 96, 99])>

<h2 style="font-family:Georgia;">14. One-hot encoding</h2>

<p style="font-family:Georgia;font-size:1.5rem; text-align:justify">Le “One Hot Encoding” est une méthode utilisée en apprentissage automatique pour quantifier les données catégorielles. En bref, cette méthode produit un vecteur dont la longueur est égale au nombre de catégories dans l’ensemble de données. Si un point de données appartient à la ième catégorie, alors les composants de ce vecteur sont attribués à la valeur 0 sauf pour le ième composant, qui se voit attribuer une valeur de 1 voici un exemple :</p>

<img src="images/onehot.png" alt="Tensor" style="float: center; width : 60%"><br><br>

In [5]:
# Creons une liste 

liste = [1,2,3,4,5,6,7]

In [6]:
# One-hot encoing : 

tf.one_hot(liste, depth=7)

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
tf.one_hot(liste, depth=7,on_value="On", off_value="Off")

<tf.Tensor: shape=(7, 7), dtype=string, numpy=
array([[b'Off', b'On', b'Off', b'Off', b'Off', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off', b'Off', b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'On'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off']],
      dtype=object)>